import { Project } from '@/types/project'

export const projects: Project[] = [
  {
    slug:        'stellar-dashboard',
    title:       'Stellar Dashboard',
    subtitle:    'Real-time analytics platform',
    description: 'A high-performance analytics dashboard built with React, D3, and WebSockets. Processes over 1M events per day with sub-100ms latency. Features live charts, custom theming, and an accessible data table system.',
    tags:        [{ label: 'React' }, { label: 'D3.js' }, { label: 'WebSocket' }, { label: 'TypeScript' }],
    image:       '/images/project-1.jpg',
    liveUrl:     'https://example.com',
    githubUrl:   'https://github.com',
    year:        2024,
    featured:    true,
    color:       '#FACC15',
  },
  {
    slug:        'morphic-ui',
    title:       'Morphic UI',
    subtitle:    'Open-source component library',
    description: 'A zero-dependency React component library with 60+ components, full a11y support, and a themeable design token system. Downloaded 40k+ times on NPM.',
    tags:        [{ label: 'React' }, { label: 'CSS-in-JS' }, { label: 'Storybook' }, { label: 'Rollup' }],
    image:       '/images/project-2.jpg',
    githubUrl:   'https://github.com',
    year:        2024,
    featured:    true,
    color:       '#a78bfa',
  },
  {
    slug:        'void-engine',
    title:       'Void Engine',
    subtitle:    '3D browser game engine',
    description: 'A lightweight WebGL game engine built from scratch on top of Three.js. Supports ECS architecture, a physics integration layer, and a visual scene editor.',
    tags:        [{ label: 'Three.js' }, { label: 'WebGL' }, { label: 'GLSL' }, { label: 'TypeScript' }],
    image:       '/images/project-3.jpg',
    liveUrl:     'https://example.com',
    githubUrl:   'https://github.com',
    year:        2023,
    featured:    true,
    color:       '#34d399',
  },
  {
    slug:        'nocturne-app',
    title:       'Nocturne App',
    subtitle:    'Focus & ambient sound app',
    description: 'A productivity app that mixes ambient soundscapes using the Web Audio API. Features a custom audio graph editor, timer modes, and offline-first PWA support.',
    tags:        [{ label: 'Next.js' }, { label: 'Web Audio API' }, { label: 'PWA' }, { label: 'Zustand' }],
    image:       '/images/project-4.jpg',
    liveUrl:     'https://example.com',
    year:        2023,
    color:       '#f472b6',
  },
  {
    slug:        'prism-cms',
    title:       'Prism CMS',
    subtitle:    'Headless content platform',
    description: 'A headless CMS with a block-based editor, real-time collaboration via CRDTs, webhook delivery system, and a GraphQL API layer.',
    tags:        [{ label: 'Node.js' }, { label: 'GraphQL' }, { label: 'PostgreSQL' }, { label: 'CRDT' }],
    image:       '/images/project-5.jpg',
    githubUrl:   'https://github.com',
    year:        2023,
    color:       '#fb923c',
  },
  {
    slug:        'arc-ml',
    title:       'Arc ML',
    subtitle:    'ML model experiment tracker',
    description: 'A self-hosted experiment tracking tool for machine learning. Compare runs, visualize metrics, and manage model artifacts with a clean, fast UI.',
    tags:        [{ label: 'Python' }, { label: 'FastAPI' }, { label: 'React' }, { label: 'SQLite' }],
    image:       '/images/project-6.jpg',
    githubUrl:   'https://github.com',
    year:        2022,
    color:       '#38bdf8',
  },
]

export const featuredProjects = projects.filter(p => p.featured)
export const getProject = (slug: string) => projects.find(p => p.slug === slug)